### ISSUE TITLE
retrieveHistoricalCandles only returning around 1500 candles

### ISSUE THREAD

**Issue by Vultwo** [agiliumtrade-ai/metaapi-node.js-sdk#32]
Hi, while getting historical candles the api only returns around 1500 candles.
(Even though there are much more candles available)
I have tried this with both G1 and G2 accounts and am using a MT4 account.
Do you guys have any idea what's going wrong?

**Comment by Vultwo** [comment]
Taken from this example: https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/blob/master/examples/retrieveHistoricalMarketData/retrieveHistoricalCandles.js

**Comment by RomanKisilenko** [comment]
Hello, the market data is provided by your broker, so that you can retrieve only as much data as your broker provides. In your local installation of MT4 which you have used for trading you can see a history of a bigger time period because you was running it across a long period of time and it accumulated some history in it's cache which is no longer available on the broker side.
