### ISSUE TITLE
Wrong tradeSessions data returned from api

### ISSUE THREAD

**Issue by abanchev** [agiliumtrade-ai/metaapi-node.js-sdk#37]
When i pull the symbol data i get the following tradingSessions
```
{
  SUNDAY: [ { from: '00:00:00.000', to: '00:00:59.999' } ],
  MONDAY: [ { from: '00:05:00.000', to: '00:00:59.999' } ],
  TUESDAY: [ { from: '00:00:00.000', to: '00:00:59.999' } ],
  WEDNESDAY: [ { from: '00:00:00.000', to: '00:00:59.999' } ],
  THURSDAY: [ { from: '00:00:00.000', to: '00:00:59.999' } ],
  FRIDAY: [ { from: '00:00:00.000', to: '23:50:59.999' } ],
  SATURDAY: [ { from: '00:00:00.000', to: '00:00:59.999' } ]
}
```

While checking on Metatrader this is what i see
![image](https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/assets/1948184/da3a42e5-f813-45e9-ad9f-f2b6ee4b6562)

The broker is XM.com and i am using a demo account for the testing

**Comment by abanchev** [comment]
Sunday and saturday should be empty, also end time should be 23:59:59.999 in this case

**Comment by abanchev** [comment]
Also some clarification in the docs would be nice, is the time in UTC, or in broker time

**Comment by RomanKisilenko** [comment]
Thank you for reporting this. The trade session data is provided by broker for each of the symbols individually.

Please contact support via online chat to investigate this further. Please make sure to provide an affected account id and symbol.

Closing this issue since it seems like it is not related to an issue in SDK.
